        
#
#   This file is part of Incipio.
#
#   Incipio is an enterprise resource planning for Junior Enterprise
#   Copyright (C) 2012-2014 Florian Lefevre.
#
#   Incipio is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   Incipio is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with Incipio as the file LICENSE.  If not, see <http://www.gnu.org/licenses/>.
#


mgate_formations_index_admin:
    pattern:  /admin/formations
    defaults: { _controller: mgateFormationBundle:Formation:index}

mgate_formations_lister:
    pattern:  /formations
    defaults: { _controller: mgateFormationBundle:Formation:lister}
    
mgate_formation_voir:
    pattern:  /formations/{id}
    defaults: { _controller: mgateFormationBundle:Formation:voir }
    requirements:
        id: \d+
        
mgate_formation_ajouter:
    pattern:  /admin/formations/ajouter
    defaults: { _controller: mgateFormationBundle:Formation:modifier, id : -1}
    
mgate_formation_modifier:
    pattern:  /admin/formations/modifier/{id}
    defaults: { _controller: mgateFormationBundle:Formation:modifier }
    requirements:
        id: \d+
        
mgate_formation_supprimer:
    pattern:  /admin/formations/supprimer/{id}
    defaults: { _controller: mgateFormationBundle:Formation:supprimer }
    requirements:
        id: \d+
        
mgate_formation_participation:
    pattern:  /admin/formations/participation
    defaults: { _controller: mgateFormationBundle:Formation:participation }
