mgate_stat:
    resource: "@mgateStatBundle/Resources/config/routing.yml"
    prefix:   /

mgate_dashboard:
    resource: "@mgateDashboardBundle/Resources/config/routing.yml"
    prefix:   /

mgate_publi:
    resource: "@mgatePubliBundle/Resources/config/routing.yml"
    prefix:   /

mgate_user:
    resource: "@mgateUserBundle/Resources/config/routing.yml"
    prefix:   /

mgateSuiviBundle:
    resource: "@mgateSuiviBundle/Resources/config/routing.yml"
    prefix:   /suivi

mgateCommentBundle:
    resource: "@mgateCommentBundle/Resources/config/routing.yml"
    prefix:   /

mgatePersonneBundle:
    resource: "@mgatePersonneBundle/Resources/config/routing.yml"
    prefix:   /personne

mgateTestBundle:
    resource: "@mgateTestBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

### FOS User start
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile   
### FOS User end


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
prospect:
    resource: "@mgatePersonneBundle/Controller/ProspectController.php"
    type:     annotation
    
    
AcmePizzaBundle:
    resource: "@AcmePizzaBundle/Controller/"
    type:     annotation
    prefix:   /acme-pizza