        
#
#   This file is part of Incipio.
#
#   Incipio is an enterprise resource planning for Junior Enterprise
#   Copyright (C) 2012-2014 Florian Lefevre.
#
#   Incipio is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   Incipio is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with Incipio as the file LICENSE.  If not, see <http://www.gnu.org/licenses/>.
#

# Domaines de comp√©tence ######################################################

mgateSuivi_domaine_index:
    pattern: /DomainesDeCompetence
    defaults: {_controller: mgateSuiviBundle:DomaineCompetence:index }

mgateSuivi_domaine_delete:
    pattern: /DomainesDeCompetence/Supprimer/{id}
    defaults: {_controller: mgateSuiviBundle:DomaineCompetence:delete }
    requirements:
      id : \d+

###############################################################################

mgateSuivi_vu_ca:
    pattern:  /ca/{id}
    defaults: {_controller: mgateSuiviBundle:Etude:vuCA, id:-1 }

mgateSuivi_etude_homepage:
    pattern:  /{page}
    defaults: {_controller: mgateSuiviBundle:Etude:index , page: 1}
    requirements:
      page : \d*

mgateSuivi_etude_ajax:
    pattern:  /get
    defaults: {_controller: mgateSuiviBundle:Etude:getEtudesAsync}

mgateSuivi_etude_suivi:
    pattern: /etudes/suivi
    defaults: {_controller: mgateSuiviBundle:Etude:suivi}
    
mgateSuivi_etude_suiviQualite:
    pattern: /etudes/suiviQualite
    defaults: {_controller: mgateSuiviBundle:Etude:suiviQualite}
        
mgateSuivi_etude_ajouter:
    pattern: /etude/ajouter
    defaults: {_controller: mgateSuiviBundle:Etude:add}

mgateSuivi_etude_voir:
    pattern:   /etude/{numero}
    defaults: {_controller: mgateSuiviBundle:Etude:voir}
    requirements:
        numero:  \d+

mgateSuivi_etude_modifier:
    pattern: /etude/modifier/{numero}
    defaults: {_controller: mgateSuiviBundle:Etude:modifier}
    requirements:
        numero:  \d+

mgateSuivi_etude_supprimer:
    pattern: /etude/supprimer/{numero}
    defaults: {_controller: mgateSuiviBundle:Etude:delete}
    requirements:
        numero: \d+      

mgateSuivi_ap_voir:
    pattern: /ap/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Ap:voir}
    requirements:
        id: \d+

mgateSuivi_ap_rediger:
    pattern: /ap/rediger/{id}
    defaults: {_controller: mgateSuiviBundle:Ap:rediger}
    requirements:
        id: \d+

mgateSuivi_ap_suivi:
    pattern: /ap/suivi/{id}
    defaults: {_controller: mgateSuiviBundle:Ap:suivi}
    requirements:
        id: \d+
        
mgateSuivi_cc_rediger:
    pattern: /cc/rediger/{id}
    defaults: {_controller: mgateSuiviBundle:Cc:rediger}
    requirements:
        id: \d+ 

mgateSuivi_cc_voir:
    pattern: /cc/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Cc:voir}
    requirements:
        id: \d+

mgateSuivi_cc_suivi:
    pattern: /cc/suivi/{id}
    defaults: {_controller: mgateSuiviBundle:Cc:suivi}
    requirements:
        id: \d+   

mgateSuivi_mission_rediger:
    pattern: /mission/rediger/{id}
    defaults: {_controller: mgateSuiviBundle:Mission:rediger}
    requirements:
        id: \d+

mgateSuivi_missions_modifier:
    pattern: /missions/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Missions:modifier}
    requirements:
        id: \d+

#AJOUT AJAX

mgateSuivi_mission_avancement:
    pattern: /missions/modifier/avancement/
    defaults: {_controller: mgateSuiviBundle:Mission:avancement}

mgateSuivi_state:
    pattern: /suivi/state/
    defaults: {_controller: mgateSuiviBundle:Etude:state}

#mgateSuivi_missions_repartition:
#    pattern: /missions/repartition/{id}
#    defaults: {_controller: mgateSuiviBundle:MissionsRepartition:index}
#    requirements:
#        id: \d+        
        

mgateSuivi_clientcontact_ajouter:
    pattern: /clientcontact/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:ClientContact:add}
    requirements:
        id: \d+

mgateSuivi_clientcontact_modifier:
    pattern: /clientcontact/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:ClientContact:modifier}
    requirements:
        id: \d+
        
mgateSuivi_clientcontact_voir:
    pattern: /clientcontact/voir/{id}
    defaults: {_controller: mgateSuiviBundle:ClientContact:voir}
    requirements:
        id: \d+     
        
mgateSuivi_clientcontact_index:
    pattern: /clientcontact/
    defaults: {_controller: mgateSuiviBundle:ClientContact:index}
       
        
mgateSuivi_suivi_ajouter:
    pattern: /suivi/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Suivi:add}
    requirements:
        id: \d+
        
mgateSuivi_suivi_modifier:
    pattern: /suivi/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Suivi:modifier}
    requirements:
        id: \d+
        
mgateSuivi_suivi_voir:
    pattern: /suivi/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Suivi:voir}
    requirements:
        id: \d+     
        
mgateSuivi_suivi_index:
    pattern: /suivi
    defaults: {_controller: mgateSuiviBundle:Suivi:index}
    
        
mgateSuivi_av_ajouter:
    pattern: /av/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Av:add}
    requirements:
        id: \d+
        
mgateSuivi_av_modifier:
    pattern: /av/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Av:modifier}
    requirements:
        id: \d+
        
mgateSuivi_av_voir:
    pattern: /av/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Av:voir}
    requirements:
        id: \d+
        
mgateSuivi_avmission_ajouter:
    pattern: /avmission/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:AvMission:add}
    requirements:
        id: \d+
        
        
mgateSuivi_avmission_voir:
    pattern: /avmission/voir/{id}
    defaults: {_controller: mgateSuiviBundle:AvMission:voir}
    requirements:
        id: \d+
        
        
mgateSuivi_avmission_modifier:
    pattern: /avmission/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:AvMission:modifier}
    requirements:
        id: \d+
          
mgateSuivi_phases_modifier:
    pattern: /phases/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Phases:modifier}
    requirements:
        id: \d+

mgateSuivi_procesverbal_ajouter:
    pattern: /procesverbal/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:add}
    requirements:
        id: \d+
      
mgateSuivi_procesverbal_modifier:
    pattern: /procesverbal/modifier/{id_pv}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:modifier}
    requirements:
        id: \d+
        
mgateSuivi_procesverbal_rediger:
    pattern: /procesverbal/rediger/{id_etude}/{type}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:rediger}
    requirements:
        id: \d+
 
mgateSuivi_procesverbal_voir:
    pattern: /procesverbal/voir/{id}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:voir}
    requirements:
        id: \d+
        
mgateSuivi_procesverbal_supprimer:
    pattern: /procesverbal/supprimer/{id_pv}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:delete}
    requirements:
        id: \d+
        
mgateSuivi_etude_suivi_update:
    pattern:  /suivi/update/{id}
    defaults: { _controller: mgateSuiviBundle:Etude:suiviUpdate }
    requirements:
        _method:  POST
        
mgateSuivi_groupes_modifier:
    pattern: /groupes/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:GroupePhases:modifier}
    requirements:
        id: \d+