parameters:
    mgate.etude_manager.class: mgate\SuiviBundle\Manager\EtudeManager
    mgate.doctype_manager.class: mgate\SuiviBundle\Manager\DocTypeManager
    mgate.chart_manager.class: mgate\SuiviBundle\Manager\ChartManager
    mgate.validation.class: mgate\SuiviBundle\Validation\Validation
    tva: 0.196

services:
    mgate.etude_manager:
        class: "%mgate.etude_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
          - "%tva%"
        tags:
            - { name: twig.extension }
    mgate.doctype_manager:
        class: "%mgate.doctype_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
    mgate.chart_manager:
        class: "%mgate.chart_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
          - "%tva%"
          - "@mgate.etude_manager"
          - "@logger"
          
    mgate.validation:
      class: "%mgate.validation.class%"
      arguments:
        - "@doctrine.orm.entity_manager"
      tags:
        - { name: twig.extension }
        
    form.type_extension.help_message:
        class: mgate\SuiviBundle\Form\Extension\HelpMessageTypeExtension
        tags:
          - { name: "form.type_extension", alias: "form" }