mgate_publi_publiposter:
    pattern: /Documents/Publiposter/{templateName}/{rootName}/{rootObject_id}
    defaults: {_controller: mgatePubliBundle:Traitement:publiposter}
    requirements:
        rootObject_id:  \d+
        rootName: \w+
        templateName: \w+
    
mgate_publi_telecharger:
    pattern: /publi/publiposter/telecharger
    defaults: {_controller: mgatePubliBundle:Traitement:telecharger}

mgate_publi_documenttype_upload:
    pattern: /DocumentsType/Upload
    defaults: {_controller: mgatePubliBundle:Traitement:uploadNewDoctype}  
        
        
######################
# UPLOAD DE DOCUMENT #
######################
mgate_publi_documenttype_index:
    pattern: /Documents
    defaults: {_controller: mgatePubliBundle:Document:index}

mgate_publi_document_uploadEtude:
    pattern: /Documents/Upload/Etude/{etude_id}
    defaults: {_controller: mgatePubliBundle:Document:uploadEtude}
    requirements:
        etude_id:  \d+
        
mgate_publi_document_uploadEtudiant:
    pattern: /Documents/Upload/Etudiant/{membre_id}
    defaults: {_controller: mgatePubliBundle:Document:uploadEtudiant}
    requirements:
        membre_id:  \d+

mgate_publi_document_uploadFormation:
    pattern: /Documents/Upload/Formation/{id}
    defaults: {_controller: mgatePubliBundle:Document:uploadFormation}
    requirements:
        id:  \d+
        
mgate_publi_document_uploadDoctype:
    pattern: /Documents/Upload/Doctype
    defaults: {_controller: mgatePubliBundle:Document:uploadDoctype}

mgate_publi_document_delete:
    pattern: /Documents/Supprimer/{id}
    defaults: {_controller: mgatePubliBundle:Document:delete}
    requirements:
        id:  \d+
  